### ISSUE TITLE
Wrong item and texture header titles

### ISSUE THREAD

**Issue by CodeRedDev** [qbcore-framework/qb-clothing#102]
I've noticed that the titles for item and texture headers in the HTML document are not set in the UI element. I've searched the whole repo and couldn't find why the headers will always display `item` and `texture` instead of the titles defined in the HTML document.

![image](https://user-images.githubusercontent.com/27018054/161661755-3edcd890-2901-4ca3-bae2-cb62a330c286.png)

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-clothing/blob/cb76b1a8f7dcc979f3cabf9a792f7f93925971c6/html/script.js#L520
