### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by BennUzi** [qbcore-framework/qb-clothing#11]
Detailed face shapes can come and the intensity can be adjusted in the beard parts, there is a bug, some players are using it maliciously, we made this in our own server by making the man invisible on our server, so that he only crashes, otherwise the whole server can crash, all players can be dropped from the game if we pass the maximum number in face setting or other things in writing and we get it back.

https://streamable.com/4g19ya

**Comment by ihyajb** [comment]
Could not reproduce the issue running the newest build.
