### ISSUE TITLE
Differentiate the shop 

### ISSUE THREAD

**Issue by GiandoSaba** [qbcore-framework/qb-clothing#110]
I would like to differentiate the shop for the various 'areas' in which it is located.
For example: in the clothes shop I would like to deny the ability to change face and face_2, and at the barber shop I would like to deny the possibility of changing facial features.

Do you have any ideas on how to proceed?

**Comment by RalivTV** [comment]
I have the same problem

**Comment by Rcanabis** [comment]
up any fix?

**Comment by GhzGarage** [comment]
The way this resource is written it requires editing the html, hoping to change that
