### ISSUE TITLE
Admin perms removed after restart QBCore

### ISSUE THREAD

**Issue by bk4cs** [qbcore-framework/qb-clothing#111]
When I restart the server, my permissions disappear. Does anyone know what the problem is?
Thanks!

**Comment by FildonPrime** [comment]
Hi @bk4cs 
If you're in using the latest update, the permission system was switched. 
You can follow `#set-permissions` channel in QBCore discord to setup your permissions.

**Comment by bk4cs** [comment]
Thank you :)
