### ISSUE TITLE
Hat, Glasses problem

### ISSUE THREAD

**Issue by philipx2017** [qbcore-framework/qb-clothing#112]
If someone punches you, you can't get back your hat or glasses! Only if you go to your apartment and change the outfit and change back.

**Comment by GhzGarage** [comment]
I'll look into this, thanks

**Comment by izMystic** [comment]
do /refreshskin

**Comment by rhapidfyre** [comment]
Not a bug, intended feature per a closed issue.

https://github.com/qbcore-framework/qb-clothing/issues/48

I added it to my server, works fine.

Might be a good idea though to make this a config setting. I might try to branch off main and do a PR to add it.

**Comment by rhapidfyre** [comment]
https://github.com/qbcore-framework/qb-clothing/pull/117

Done
