### ISSUE TITLE
Refreshskin BUG

### ISSUE THREAD

**Issue by ShomyTKD** [qbcore-framework/qb-clothing#115]
There's a huge problem with /refreshskin command. If you type it multiple times in a row, it will heal you. Could you please have a look at it?

**Comment by jnccloud** [comment]
What's the importance of this function? I'm not so positive I've ever had anyone use it. But it does appear to be a bit messy.

```lua
RegisterCommand("refreshskin", function(source, args, rawCommand)
    local playerPed = PlayerPedId()
    local maxhealth = GetEntityMaxHealth(playerPed)
    local health = GetEntityHealth(playerPed)
    reloadSkin(health)
end)

function reloadSkin(health)

    local model = nil
    local gender = QBCore.Functions.GetPlayerData().charinfo.gender

    if gender == 1 then -- Gender is ONE for FEMALE
    model = GetHashKey("mp_f_freemode_01") -- Female Model
    else
    model = GetHashKey("mp_m_freemode_01") -- Male Model
    end

    RequestModel(model)

    SetPlayerModel(PlayerId(), model)
    SetModelAsNoLongerNeeded(model)
    Citizen.Wait(1000) -- Safety Delay

    TriggerServerEvent("qb-clothes:loadPlayerSkin") -- LOADING PLAYER'S CLOTHES
    TriggerServerEvent("qb-clothing:loadPlayerSkin") -- LOADING PLAYER'S CLOTHES - Event 2

    SetPedMaxHealth(PlayerId(), maxhealth)
    Citizen.Wait(1000) -- Safety Delay
    SetEntityHealth(PlayerPedId(), health)
end
```

**Comment by ShomyTKD** [comment]
It is very useful when some objects get stuck in player's hqnds. For example, a lot of times when players use cleaning kit to clean their car, towel gets stuck in their hand and disappears only when they relog or when they use /refreshskin.

Note: I actually fixed this by using cooldown of 1-2 seconds between executing commands :) Not the perfect solution but it works for me.

**Comment by jnccloud** [comment]
Ah, Ok I see. I'm not sure how optimized this is, but this is the command I use for that same reason. (Also if you use dpemotes, `/e smoke` is great as well). Just stick it in a client script. You don't have to worry about the health events etc like you see in this function.

```lua
RegisterCommand('propstuck', function()
    for k, v in pairs(GetGamePool('CObject')) do
      if IsEntityAttachedToEntity(PlayerPedId(), v) then
        SetEntityAsMissionEntity(v, true, true)
        DeleteObject(v)
        DeleteEntity(v)
      end
    end
end)
```

**Comment by ShomyTKD** [comment]
Oh great, thank you! I will try it out!
