### ISSUE TITLE
add on clothing not showing

### ISSUE THREAD

**Issue by ReV0official** [qbcore-framework/qb-clothing#119]
Having a problem with add on clothing not showing up in the menu.
i previously used this pack in esx and it worked fine.
server key is up to date allowing clothing.

**Comment by Thegygantor** [comment]
I really hope someone replies to you about this issue because I’m having same issues where the custom clothing I’m adding isn’t showing up In clothing shops no matter what

**Comment by Grant-Daniels-Dev** [comment]
You need to stream the clothing and make sure that you have a cfx patreon setup :)

**Comment by itsluap** [comment]
I have the same issue, my addon clothes are streaming and I can access them via other menus but qb-clothing doesn't have them

**Comment by Wildeman13** [comment]
I am running into the same problem. Have tried it both using a "manually" streamed resource as well as a built package using DurtyCloth tool and both previosuly worked fine when running a QBCore server via ZAP hosting. But after switching to a locally hosted QBCore and presumably updated qb-XX resources, I can't get any of my custom streamed clothing packs to show up in the clothing store.

**Comment by MentalIllness** [comment]
Basically when you add custom clothes, they are replacing other clothes' textures so qb-clothing is just selecting these textures and setting them on your character. So the problem shouldn't be related to qb-clothing.

**Comment by ShamelessGames** [comment]
I'm having the same problem I've tried everything I was told I even bought a sub to make sure the custom clothes could be streamed and still nothing comes up
