### ISSUE TITLE
Loading into the server in a PolyZone

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-clothing#121]
Getting the client side exception shown below when you fly into the server and load into a character that's position was last within the PolyZone. This also causes the clothing script not to work for that specific character until you move your character out of the PolyZOne and close then reload into the server.

![image](https://user-images.githubusercontent.com/43043270/166467584-bef0da60-4460-4f62-ad8d-f41092602cff.png)

**Comment by JustGeezyGames** [comment]
There's multiple scripts that has this same issue. Would love to hear how other people address it.

**Comment by MentalIllness** [comment]
Error fixed in the current version.
