### ISSUE TITLE
i can change a face on a shop and i don't need that

### ISSUE THREAD

**Issue by evatv** [qbcore-framework/qb-clothing#122]
i can change a face on a shop and i don't need that i need remove that line from shop pls help

**Comment by evatv** [comment]
Hey, is it possible to remove the face changing options from the clothing shops once a player makes his character ?

**Comment by Grant-Daniels-Dev** [comment]
Yes, it's already implemented! :)

**Comment by Grant-Daniels-Dev** [comment]
Check the config options! There are many! :)

**Comment by Kiskoroal** [comment]
How can you solve it?

**Comment by C12704XGUNCORE** [comment]
> Oui, c’est déjà mis en œuvre ! :)

Bonjour comment avez-vous fait ?

**Comment by MentalIllness** [comment]
Issue should be fixed in the next merge.
