### ISSUE TITLE
[BUG] Clothes are not being taken off

### ISSUE THREAD

**Issue by W0lv3sxD** [qbcore-framework/qb-clothing#127]
**Describe the bug**
After adding addon clothes the clothes are not being taken off, instead they are just changing.

**To Reproduce**
Take off a piece of clothing

**Expected behavior**
I expect it to take off the piece of clothing. Shirt for example should be taken off so I'm half naked.

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/93610323/168325214-09d95b7d-ac77-4b20-81d4-1bec6d5c5b53.png)

After
![image](https://user-images.githubusercontent.com/93610323/168325272-67256e81-861a-41d7-8200-8dd4c7fbd2c1.png)

**Questions (please complete the following information):**
 - When you last updated: [I have the newest version]
 - Are you using custom resource? which ones? [No]
 - Have you renamed `qb-` to something custom? [No]

**Additional context**
I hope someone can help me.
Thanks in advance.

**Comment by Grant-Daniels-Dev** [comment]
You'd need to go over to qb-radialmenu and change the values there. CTRL + F and look for "drawable" usually is the problem!

**Comment by CLRPUK** [comment]
> 

What do i need to change
