### ISSUE TITLE
[BUG] Hair reverts to previous preset Outfits on relog.

### ISSUE THREAD

**Issue by Duderocktv** [qbcore-framework/qb-clothing#128]
**Describe the bug**
Fully updated qbcore with qb-clothing.

Everytime players relog, the hair changes back to an old hairstyle.
The outfits are saved with the proper hairstyles, but it keeps reverting the hair?

**To Reproduce**
1. Create a character with an outfit and a hair style
2. Save the outfit.
3. Create a new outfit, with a different hairstyle
4. Save that outfit as well.
5. Log out and log back in on Outfit #2, your hair will be Outfit #1

**Expected behavior**
Instead of Outfit #1 hair on Outfit #2, it should be Outfit #1.

**Screenshots**

**Questions (please complete the following information):**
 - Completely up to date
 - No Custom Resoources
 - No Renames

**Additional context**

**Comment by Grant-Daniels-Dev** [comment]
You have absolutely no custom resources that alter the peds clothing? I find that hard to believe, but let's go with it for now. 
Can't put my finger on replicating this issue, but I believe your database might be corrupt or some value inside might be too high for the varchar limit or something close in it's nature. Could you check?
