### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Thegygantor** [qbcore-framework/qb-clothing#129]
-custom clothing not showing up-

I have openiv and going through all these guides on YouTube etc and nothing works. Issue is no clothing (custom) are showing up in shops.

**Comment by InuuYashaa** [comment]
Same issue

**Comment by rollingozs** [comment]
Make sure you have properly streamed the files, and renamed them properly. :)

**Comment by Wildeman13** [comment]
> Make sure you have properly streamed the files, and renamed them properly. :)

Can you give some guidance here? In previous ESX based servers, the names my custom clothing had didn't seem to matter, but with qb-clothing I'm having the same issue as the OP as I cannot seem to get my custom clothing to show up. 

my old custom package used mostly default naming...

mp_m_freemode_01_mp_m_january2016^task_010_u.ydd 
mp_m_freemode_01_mp_m_january2016^task_diff_010_a_uni.ytd

I have tried changing the names to task_030_XX but that didn't seem to do anything after restarting the resource.

**Comment by Wildeman13** [comment]
I have finally figured out my issue... I was running the default 48player levels and didn't know about the requirement for under 10players for streaming clothes unless you have the license from FiveM
