### ISSUE TITLE
Gang clothing stores not working?  [BUG]

### ISSUE THREAD

**Issue by ashleyjrobinson** [qbcore-framework/qb-clothing#134]
**Describe the bug**
When using isGang = true and setting coords, nothing is displaying?

**Expected behavior**
The ability to set gang lockers

**Comment by rollingozs** [comment]
I've personally tested this, and it's working. I'd have to say you are maybe missing a small comma or something so slight! It's okay we all run into it! 
Best way for you to check, is go to txAdmin server console click the button "Download Log" and open with your favorite Text Editor. Mines MobaXTerm. :)
Search using CTRL + F the term "qb-clothing" and look and see if you see any syntax errors. Let me know the results!
