### ISSUE TITLE
[SUGGESTION] Clothes shop and Barber

### ISSUE THREAD

**Issue by amgmacht** [qbcore-framework/qb-clothing#138]
The script is really cool, yes, but I would wish :D that you could only choose clothes in a clothes shop and not be able to recreate your character, as well as with baber the only thing that really works is at the job wardrobe there you can only change clothes.

please try to change that if it is still possible.

**Comment by DanielHristov** [comment]
#136

**Comment by amgmacht** [comment]
okay but is that out in the character creation?
