### ISSUE TITLE
[BUG] gang wardrobe

### ISSUE THREAD

**Issue by amgmacht** [qbcore-framework/qb-clothing#139]
we have the problem that the gang wardrobe cannot be opened and we get this error here:

1. https://prnt.sc/UEOM1OWXd17h
2. https://prnt.sc/tGjZSqjESJIt

**Comment by rollingozs** [comment]
If I had to take a guess from the provided information, I would say that you a database structure issue, or you haven't properly installed the qb-core main player tables which could be done automatically if you update to the latest artificat as well as txadmin.

**Comment by amgmacht** [comment]
I updated the artefact version a short time ago and I also compared the table in the database with the last version of github and it looks the same from the pure sequence and still there is always this one error

**Comment by Grant-Daniels-Dev** [comment]
okay, well try to reinstall the qb-clothing completely?

**Comment by amgmacht** [comment]
the thing with the gadarobe gang didn't work right from the start and even if I do it again, the same error comes up again, all the others just don't work with the gadarobe gang

**Comment by SayNoForDoping** [comment]
problem still exists..
