### ISSUE TITLE
[BUG] refreshskin crashes FiveM

### ISSUE THREAD

**Issue by JonasDev99** [qbcore-framework/qb-clothing#140]
When doing /refreshskin on the latest recipe and latest build the game crashes if your character is a ped skin.

![image](https://user-images.githubusercontent.com/25738474/177036227-00034ccf-4491-49e2-b586-7326759016e6.png)

![image](https://user-images.githubusercontent.com/25738474/177036562-6b684894-e6ff-429c-983e-634a606990fc.png)

1. Get a clean install of QBCore and set sv_enforceGameBuild 2612 (I have not tested it on any other gamebuilds but I think its the same)
2. Change your character to a ped skin
3. execute command /refreshskin

**Expected behavior**
It should refresh the skin

I assume its trying to apply clothing to the pedskin which of course fails as its not supported.

**Comment by rollingozs** [comment]
Is there any type of errors that come with it?

**Comment by Townyo420** [comment]
is it crazy that im getting this same error in 2024? and if so how do i fix this? because its starting to drive me fucking nuts
