### ISSUE TITLE
/shirt, /pants, /shoes and etc [HELP]

### ISSUE THREAD

**Issue by elmschaym** [qbcore-framework/qb-clothing#141]
Where can I find this command? which folder?

**Comment by rollingozs** [comment]
If you are trying to fix your /hat /shirt commands I'd suggest going to qb-radialmenu
https://github.com/qbcore-framework/qb-radialmenu/blob/1848514e137ff90b791c84f2032f038ed026f949/client/clothing.lua
And changing your drawable number on each corresponding section to make them actually work.
