### ISSUE TITLE
[BUG] gang wardrobe not working when qb-target is enabled

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-clothing#142]
gang wardrobe not working when qb-target is enabled

[8] = {requiredJob = "lostmc", isGang = true, coords = vector3(986.69, -92.71, 74.85), width = 2, length = 2, cameraLocation = vector4(984.97, -90.71, 74.85, 223.05)}

[qb-target = false] no problem found
![image](https://user-images.githubusercontent.com/108535266/179431525-db047785-cb49-4ea1-97bb-f3c4e6809901.png)

[qb-target = true] target not found
![image](https://user-images.githubusercontent.com/108535266/179431552-c7557b06-61c6-4f74-abff-7500245551c3.png)

**Comment by rollingozs** [comment]
You are going to have to change using target to true or false in your config.cfg file. :)

**Comment by rollingozs** [comment]
Have you resolved this, or could you tell me a little more about the issue?
Could you possibly download your server log from txadmin server console and Ctrl + F and search for qb-clothing?
