### ISSUE TITLE
[SUGGESTION] access to model changes

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-clothing#143]
The user group does not have access to the model change.

The admin group has access to change the model.

![image](https://user-images.githubusercontent.com/108535266/179435584-19c927f6-7439-4e58-9f27-6ca4aa0033c1.png)

**Comment by Postmortemgamer** [comment]
The truth would be very good to remove that and only leave it for authorized users or with permissions, I have also wanted to know how to remove it for a long time if someone knew how it would be great.

**Comment by rollingozs** [comment]
I believe that is something we could prevent, most defintely!
