### ISSUE TITLE
[BUG] Facial Features not syncing

### ISSUE THREAD

**Issue by PretDevTective** [qbcore-framework/qb-clothing#147]
Using the barber side of the clothing menu, the player is able to customize the models face, nose, chin, jaw, etc. Through some testing it's clear that not all facial features are syncing from one client to another as displayed in the images below, "extremes" being possible, the client who is customizing might be able to make their characters twice as long as it is visually seen on a nearby client. 

I'm assuming this is because the player should not be able to customize f.e. their nose length down to 30, although the menu allows it. **Sane values seem to sync correctly.**

1. Open features menu in qb-clothing and put your facial features to the max (f.e. Butt Chin to 30)
2. Confirm and have second client observe your player model.
3. Compare.

Client 1 (the one who is customizing their model) should see an extreme difference in their model, but Client 2 (observer) is only able to see the "sane" value of that customization.

First picture is Client 1, second picture is Client 2 (observer)
![expl2](https://user-images.githubusercontent.com/112201632/186971258-40699dd5-db66-4bfe-8100-959684e7fc7c.png)
![expl1](https://user-images.githubusercontent.com/112201632/186971261-67ee5cde-f2cc-4fbf-8766-fc017fc92f8c.png)

 - When you last updated: [e.g. last week] **Latest QB-Clothing**
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] **No**
 - Have you renamed `qb-` to something custom? [e.g. yes/no] **No**

**Comment by PretDevTective** [comment]
Sane values seem to be between -10 and +10, any further than that and features won't sync.

**Comment by rollingozs** [comment]
I'm going to test this out, and see if I can recreate it. I've personally enver heard of this.

**Comment by Grant-Daniels-Dev** [comment]
Have you tested this with female characters as well?

**Comment by PretDevTective** [comment]
> 

No, only male ped. Shouldn't be hard to recreate either.

**Comment by Grant-Daniels-Dev** [comment]
I believe if you update to the newest version you won't have that issue. I have done multiple test, and no results.

**Comment by Exyztence** [comment]
> I believe if you update to the newest version you won't have that issue. I have done multiple test, and no results.

May I have a contact to you? Discord ain't working
