### ISSUE TITLE
[BUG] Ped Model incompatibility 

### ISSUE THREAD

**Issue by Shotoki** [qbcore-framework/qb-clothing#155]
**Describe the bug**
When adding a custom Character Ped Model and selecting HAIR variations - the default menu causes the hair rigging to go crazy *attached screenshots* 

If anyone has a fix it would greatly be appreciated. 

**To Reproduce**
1. Add custom ped model -- Modify config.lua in qb-clothing root / under Config.ManPlayerModels = {   **add name of ped.meta  'Name' } - Save 
2. Restart qb-clothing 
3. Visit clothing store or use admin panel to provide Clothing menu to player.   Under Model - select ped model name 
4. PED should load up clearly
5. Go to hair tab and select option greater than 1.  result is attached in screenshot  - See Error

Installed vMenu for testing, ped model spawns and all configuration options are accessible. I am assuming this is due to scripting of vMenu being separate form QBcore. 

**Expected behavior**
As with previous server builds I expected the model selection to be available - the clothing options to select the various streamed content from the file. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/90734096/198723041-7adbf697-0b4f-485e-b314-1bb988a8b25b.PNG)
![Capture2](https://user-images.githubusercontent.com/90734096/198723042-485cf2e5-4fe2-430c-86a0-9ec3dc31ee2f.PNG)
![Capture3 no issue](https://user-images.githubusercontent.com/90734096/198723043-22c50389-d6a8-41c4-8f67-bfc468eb0ce5.PNG)

**Questions (please complete the following information):**
 - New QB Installation (dev server)
 - Are you using custom resource? which ones? none
 - Have you renamed `qb-` to something custom?  no

**Additional context**

**Comment by Shotoki** [comment]
Seems to be an ongoing topic as the qb-clothing menu is sourced from fivem-appearance script. Will follow bug reports in fivem-appearance as well https://github.com/pedr0fontoura/fivem-appearance/issues/36

**Comment by MentalIllness** [comment]
The bug is not related to qb-clothing

**Comment by Galaxyz7** [comment]
This is definitely qb-clothing as changing ped with vmenu works fine,

Another thing to note is when setting ped with qb-clothing menu there were no running sounds and the game crashed when hit by vehicles and sometimes caused others to crash around them

**Comment by LYRYCAL** [comment]
Any progress on this?
