### ISSUE TITLE
[BUG] changing playerskins

### ISSUE THREAD

**Issue by Exyztence** [qbcore-framework/qb-clothing#156]
**Describe the bug**
People on the server at random times (after entering the server or entering qb-clothing in shop etc.) receive other people's playerskin. 

**To Reproduce**
Don't have an idea how to reproduce it, it is completely random

**Expected behavior**
Have their own playerskin

**Screenshots**
Example of my friend.
**His normal character:** https://media.discordapp.net/attachments/1014557428525834281/1036709738005672046/unknown.png?width=1635&height=910
**After bug:** https://media.discordapp.net/attachments/1014557428525834281/1036707202720878644/unknown.png

**Questions (please complete the following information):**

**When you last updated: [e.g. last week]**
- Newest qb-multicharacter
**Are you using custom resource? which ones? [e.g. zdiscord, qb-target]**
- No, just changed style.css of qb-multicharacter, nothing else
**Have you renamed qb- to something custom? [e.g. yes/no]**
- No

**Comment by Exyztence** [comment]
fixed

**Comment by singh-manavv** [comment]
This is resolved so i will be closing this thread
