### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by thebu1let** [qbcore-framework/qb-clothing#161]
When attempting to open the clothing menu for any job I am getting a error clothing shops are working fine it is just for job

1. Go to 'MRPD'
2. Click on 'go to the locker room attempt to open the clothing locker'
3. See error in F8 Console

![image](https://user-images.githubusercontent.com/82245287/208264342-f440499a-4a89-4c69-9945-ba2935e93389.png)

 - When you last updated: 12/17/2022
 - Are you using custom resource? which ones? qb-clothing
 - Have you renamed `qb-` to something custom? No

**Comment by MentalIllness** [comment]
This issue should be fixed in the next update ( ETA: 24 hours from now )
