### ISSUE TITLE
[BUG] qb-clothing

### ISSUE THREAD

**Issue by killzone185** [qbcore-framework/qb-clothing#162]
With a fresh install of QBCore from txadmin adding correct spots for qb-clothing at the police station the menu for the police to pick there clothes out will not pop up. The only way to correct that is if you do a script restart. So i've taken an older qb-clothing and works fine. I think the qb-jobs is messing the script up.

**To Reproduce**
Go to any police station or ambulance job no menu pops up
4. No

**Expected behavior**
For the menu to pop up

**Questions (please complete the following information):**
 - When you last updated: [Yesterday Fresh install]
 - Are you using custom resource? which ones? [No using any custom scripts]
 - Have you renamed `qb-` to something custom? [No]

**Additional context**
None

**Comment by FlashModz** [comment]
Same error for me

**Comment by JordanBScott** [comment]
Same here unfortunately

**Comment by twigmasters** [comment]
I am having the same problem. Anyone find a fix for it yet?

**Comment by Ap1na** [comment]
same problem

**Comment by C12704XGUNCORE** [comment]
egalement

**Comment by josh7833** [comment]
I get the same problem is there still no fix to this? I can never get the clothing to show up I even changed the location. I will have to keep trying to figure it out as I figured it would all work with a fresh copy installed.

**Comment by MentalIllness** [comment]
This issue should be fixed in the next update ( ETA: 24 hours from now )
