### ISSUE TITLE
Clothing Police Can‘t open

### ISSUE THREAD

**Issue by CHAlessio** [qbcore-framework/qb-clothing#164]
If I want to open the shop via qb target for the PD I get this error

SCRIPT ERROR: @qb-clothing/client/main.lua:1207: attempt to index a nil value (upvalue 'data')

i have nothing changed only this error comming up

**Comment by cammygames** [comment]
I managed to get mine working by editing these 2 lines

https://github.com/qbcore-framework/qb-clothing/blob/main/client/main.lua#L1911
https://github.com/qbcore-framework/qb-clothing/blob/main/client/main.lua#L1917

`getOutfits(gradeLevel, Config.Outfits[v.requiredJob])`

**Comment by erikmeyer08** [comment]
works for me!

**Comment by Asogaming** [comment]
> works for me!

What changes did you make to those lines?

**Comment by DinoCROTH** [comment]
> > works for me!
> 
> What changes did you make to those lines?

ClothingRooms

**Comment by wendelbb** [comment]
i have tried 3 different ways and i still get the same error as above...

getOutfits(gradeLevel, Config.Outfits[v.requiredJob])      < ---- broken for me

getOutfits(gradeLevel, Config.ClothingRooms[v.requiredJob])   <---- broken as well

and it doesnt work if i have both in there... 

i get the error no matter how i edit the code

SCRIPT ERROR: @qb-clothing/client/main.lua:1207: attempt to index a nil value (upvalue 'data')
