### ISSUE TITLE
[ERROR] parsing script @qb-clothing/config.lua

### ISSUE THREAD

**Issue by JensVLive** [qbcore-framework/qb-clothing#166]
**Describe the bug**
Each time when I try to start the server I'm constantly  getting an error. I've allready tried to fix the problem but nothing works.

Error:
`[  script:qb-clothing] Error parsing script @qb-clothing/config.lua in resource qb-clothing: @qb-clothing/config.lua:542: '}' expected (to close '{' at line 541) near 'for'`

**Expected behavior**
The error will pop-up.

**Screenshots**
(see attached files)

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? yes (see attached screenshots)
 - Have you renamed `qb-` to something custom? no

![image](https://user-images.githubusercontent.com/121896405/210424462-ddeeab18-ebca-4d55-a256-cb38bcf69731.png)
![image](https://user-images.githubusercontent.com/121896405/210424518-44b7b15d-7a32-4554-843e-acc07c00c789.png)
![image](https://user-images.githubusercontent.com/121896405/210424567-c358139e-998c-49ae-98b3-ed7a8f5e4382.png)
![image](https://user-images.githubusercontent.com/121896405/210424597-9765955f-3f4a-4489-bb2a-c76854733bcc.png)

[maps]
![image](https://user-images.githubusercontent.com/121896405/210424643-eb5c0978-4540-408c-8b5d-2399251ab913.png)
 
[hud]
![image](https://user-images.githubusercontent.com/121896405/210424730-2ac9174d-e9b7-42a2-8990-3f98f9c0ad51.png)

![image](https://user-images.githubusercontent.com/121896405/210424762-0dd8023b-7f79-4b61-baca-240f62d8eb00.png)

**Comment by HawkEye172** [comment]
> **Describe the bug** Each time when I try to start the server I'm constantly getting an error. I've allready tried to fix the problem but nothing works.
> 
> Error: `[ script:qb-clothing] Error parsing script @qb-clothing/config.lua in resource qb-clothing: @qb-clothing/config.lua:542: '}' expected (to close '{' at line 541) near 'for'`
> 
> **Expected behavior** The error will pop-up.
> 
> **Screenshots** (see attached files)
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: today
> * Are you using custom resource? which ones? yes (see attached screenshots)
> * Have you renamed `qb-` to something custom? no
> 
> ![image](https://user-images.githubusercontent.com/121896405/210424462-ddeeab18-ebca-4d55-a256-cb38bcf69731.png) ![image](https://user-images.githubusercontent.com/121896405/210424518-44b7b15d-7a32-4554-843e-acc07c00c789.png) ![image](https://user-images.githubusercontent.com/121896405/210424567-c358139e-998c-49ae-98b3-ed7a8f5e4382.png) ![image](https://user-images.githubusercontent.com/121896405/210424597-9765955f-3f4a-4489-bb2a-c76854733bcc.png)
> 
> [maps] ![image](https://user-images.githubusercontent.com/121896405/210424643-eb5c0978-4540-408c-8b5d-2399251ab913.png)
> 
> [hud] ![image](https://user-images.githubusercontent.com/121896405/210424730-2ac9174d-e9b7-42a2-8990-3f98f9c0ad51.png)
> 
> ![image](https://user-images.githubusercontent.com/121896405/210424762-0dd8023b-7f79-4b61-baca-240f62d8eb00.png)

You have to put a comma at the end of that line

**Comment by MentalIllness** [comment]
Local problem. Look more closely, you have missing bracket "{}" in config.lua
