### ISSUE TITLE
[BUG] Police clothing mirror throws error

### ISSUE THREAD

**Issue by S33G** [qbcore-framework/qb-clothing#169]
When attempting to choose clothing in the Police station (`vector4(454.54, -989.07, 30.69, 6.38)`) I see the following error.

```
^1SCRIPT ERROR: @qb-clothing/client/main.lua:1207: attempt to index a nil value (upvalue 'data')^7
[  25124078] [b2699_GTAProce]             MainThrd/ ^3> ref^7 (^5@qb-clothing/client/main.lua^7:1207)
[  25124078] [b2699_GTAProce]             MainThrd/ ^3> handler^7 (^5@qb-core/client/events.lua^7:207)
[  25124078] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: error object is not a string^7
```

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
I expect to choose my clothing as someone with the police job

**Screenshots**
![image](https://user-images.githubusercontent.com/655807/211403946-a5699671-2306-4115-86d6-1fae7ba896de.png)
![image](https://user-images.githubusercontent.com/655807/211403978-0a6a5dd5-3589-42ad-b2b9-7d14bf93050a.png)

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by MentalIllness** [comment]
This issue should be fixed in the next update ( ETA: 24 hours from now )
