### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrTine** [qbcore-framework/qb-clothing#171]

**Comment by JordanBScott** [comment]
Same here. Also the give clothing menu in the admin menu doesn't work either. I think they tried to fix it but it still don't work...

**Comment by LV-Soft** [comment]
Fix: https://github.com/qbcore-framework/qb-clothing/pull/172

**Comment by HyperCheetah** [comment]
> Fix: #172
@LV-Soft
I copied your file. Now it shows: 
Attempt to index a nil value field "job"

**Comment by LV-Soft** [comment]
@HyperCheetah line ?
