### ISSUE TITLE
[BUG] Get stuck after saving outfit

### ISSUE THREAD

**Issue by mspiggygaming** [qbcore-framework/qb-clothing#173]
**Describe the bug**
I installed the qb clothing file per instructions. I am able to bring up the menu to save my outfit but once I name my outfit...I cant exit out of the save menu. The menu stays on my screen. I cant hit escape to back out of the save outfits menu. I have to f8 quit. and when I go back to the server, the outfit didnt save. The save outfit menu doesnt work at clothing stores, I can only access the save outfit menu in my apartment and the clothing bag. 

**Expected behavior**
I would like to know what I need to change in the script in order for me to save clothing and not get stuck in the menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/123575509/214689860-ba1120c3-5e98-44a5-bfca-8566a4dd76fd.png)
![image](https://user-images.githubusercontent.com/123575509/214692236-f99170a0-33b9-4b59-b023-15bddf07ba50.png)

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? qb addons and fs apartments/multicharacter
 - Have you renamed `qb-` to something custom? no

**Comment by zwkf** [comment]
Looks like a database issue for resource `fivem-appearance`
