### ISSUE TITLE
[BUG] ClothingRooms shows polyzones

### ISSUE THREAD

**Issue by RaketeOriginal** [qbcore-framework/qb-clothing#174]
Suddenly the ClothingRooms are showing the polyzones .. i put the default cfg in, but it wont help

![image](https://user-images.githubusercontent.com/110101558/220206659-62ad0dbd-7935-4546-a841-b62240351543.png)

**Comment by RaketeOriginal** [comment]
And another question .. is it possible to add one ClothingRoom without Job Restriction?

**Comment by NatasWillDoIt** [comment]
> Suddenly the ClothingRooms are showing the polyzones .. i put the default cfg in, but it wont help
> 
> ![image](https://user-images.githubusercontent.com/110101558/220206659-62ad0dbd-7935-4546-a841-b62240351543.png)

did you turn on Debug in the config file ?

**Comment by RaketeOriginal** [comment]
found it - thx :)
