### ISSUE TITLE
[SUGGESTION] ClothingRooms without Job / Gang restriction

### ISSUE THREAD

**Issue by RaketeOriginal** [qbcore-framework/qb-clothing#175]
Hey, i would love to use those clothing rooms, without a gang or job restriction. 
Is it possible?

**Comment by wendelbb** [comment]
i am working on this myself because the job restriction is causing an error with my fire department job. if i figure it out, ill let you know.

**Comment by RaketeOriginal** [comment]
thx dude <3

**Comment by RaketeOriginal** [comment]
any news? @wendelbb

**Comment by wendelbb** [comment]
nope, everything i try doesnt work.

**Comment by MentalIllness** [comment]
You can configurate it via config.lua
