### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Asogaming** [qbcore-framework/qb-clothing#180]
When I join the server I can't use the clothingroom as a police officer. But when I ensure qb-clothing in the console it works perfect. (It's ensured to start on server startup.)
![error](https://user-images.githubusercontent.com/79250752/222226070-93ae2250-f080-4da4-bcd3-4d0174aafd45.png)

**Comment by Casitrompeta** [comment]
Same with all the clothingrooms
I think there are a pull being created to correct this

**Comment by DinoCROTH** [comment]
Yes. Still not working

**Comment by DeadClap** [comment]
Same

**Comment by MentalIllness** [comment]
This issue should be fixed in the next update ( ETA: 24 hours from now )
