### ISSUE TITLE
Can't show saved outfits next to clothing menu

### ISSUE THREAD

**Issue by Bankseyy** [qbcore-framework/qb-clothing#181]
Where do you access the saved outfits in the qb-clothing menu? We have configured our clothes shops but the saved outfits section is missing. 

Thanks!

**Comment by MrSchwepppes** [comment]
Bump, same issue. Not sure if this is a suggestion or a WIP or what but it really needs to be added if it isn't.

**Comment by MentalIllness** [comment]
Future should be added
