### ISSUE TITLE
qb-clothing don't work as a police

### ISSUE THREAD

**Issue by mumintim** [qbcore-framework/qb-clothing#182]
Do someone know to fix when the police can't open qb-clothing in the locker roomsa. when i restart the script it worked but then when i write /logout and try to chose my char again i just get a black loading screen.

**Comment by antpngl92** [comment]
same here, doesn't work on server starting, but once the resource is restarted through txAdmin the UI is shown

**Comment by petper** [comment]
I've been looking at this a few times, and it seems like it doesnt work when the policejob script starts after clothing. But something hicks up when restarting the script and then trying to join again.
I am looking for a solution for it.

**Comment by antpngl92** [comment]
Seems that this is a more general issue. Added custom Outfits for qb-taxi and the clothing point has the same behavior as the police outfits -  on server start the clothing does show up, and once the resource is restarted the clothing menu shows up.

**Comment by themabluerp** [comment]
Hi, I have the same problem with mine and I am running the latest version.

**Comment by MentalIllness** [comment]
This issue should be fixed in the next update ( ETA: 24 hours from now )
