### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MartinMarih** [qbcore-framework/qb-clothing#185]
I recently download my QBcore framework and I keep getting this error. Even my oxmysql is up to date. What can I do?
![Screenshot 2023-04-22 133012](https://user-images.githubusercontent.com/61891359/233805429-36493288-92da-46b1-b605-2705bbf46092.png)

**Comment by MentalIllness** [comment]
You have a local issue. If you still have this problem visit our Discord server. :)
