### ISSUE TITLE
[BUG] Clothing reset on cancel / not active unless re-ensured from cmd

### ISSUE THREAD

**Issue by DeadClap** [qbcore-framework/qb-clothing#186]
**Describe the bug**
After initial install of QBCore and setting up DB - Clothing rooms fail to work and when exiting a clothing room removes hair and or clothing set back to default ped not Characters set skin

**To Reproduce**
Go into any clothing room and hit cancel after selecting an outfit - it will default the ped
Go where a clothing room is after initial boot of the server and try to use - Its not even there

**Expected behavior**
Exiting any clothing room should return to ped skin from db

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Fresh deployment from txAdmin
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] none
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by Pskaf-Moost** [comment]
Exact same bug.
Just looked into it, apparently in client.lua, when closing the menu the script try to call client:onMenuClose but this event doesn't seem to exist

**Comment by MentalIllness** [comment]
Can you send a video of the bug, because I don't have it on my local server?

**Comment by mfel2k** [comment]
I will have to reset one of the clothing menus at some point. I have switched to just having clothing shops in the locker rooms. But Will get you something when I can.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MentalIllness** [comment]
Alright waiting for your response
