### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by gry5671** [qbcore-framework/qb-clothing#189]
How can I add custom clothing in qb-clothing menu ??

**Comment by GodyFromDiscord** [comment]
qb-clothing or any appearance related script is nothing to do with adding custom clothing, when you add custom clothing their .ymt files will create slots in any clothing menu, check out some guides on YT.

https://www.youtube.com/results?search_query=how+to+add+custom+clothing+to+your+fivem+server
