### ISSUE TITLE
[DATA BASE EROR]

### ISSUE THREAD

**Issue by gry5671** [qbcore-framework/qb-clothing#190]
Qb-clothing data base eror ![Image](https://cdn.discordapp.com/attachments/1098491865906548886/1111715942574067743/IMG_20230526_205636.jpg)

**Comment by MentalIllness** [comment]
There is a template that you have to follow before submiting a bug report. We can't help you with the current provided information.

**Comment by gry5671** [comment]
ok I whill do another one
