### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gry5671** [qbcore-framework/qb-clothing#191]
**Describe the bug**
I just updated the qb-clothing whit the new one and when I wanted to start the qb-clothing in data base it gives me an error after that when I start the server she spawn me whit default fivem peds 
**To Reproduce**
1. I open the qb-clothing (sql file) in HeidiSQL
2. I clicked on the start button 
3. And I got that error (screenshot down below)

**Expected behavior**
I expected to start the qb-sql and to work like before 

**Screenshots**
[
![image](https://github.com/qbcore-framework/qb-clothing/assets/121401014/cdd68f64-8080-4c5c-af55-c1890be59b8d)
](url)

**Comment by qb-core-dutch** [comment]
just add this


CREATE TABLE IF NOT EXISTS `playerskins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(255) NOT NULL,
  `model` varchar(255) NOT NULL,
  `skin` text NOT NULL,
  `active` tinyint(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`),
  KEY `active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `player_outfits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) DEFAULT NULL,
  `outfitname` varchar(50) NOT NULL,
  `model` varchar(50) DEFAULT NULL,
  `skin` text DEFAULT NULL,
  `outfitId` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `citizenid` (`citizenid`),
  KEY `outfitId` (`outfitId`)
) ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4;

**Comment by gry5671** [comment]
same error

**Comment by gry5671** [comment]
I just reistall all the server data base and error is solved
