### ISSUE TITLE
Player Skins resetting / not saving [BUG]

### ISSUE THREAD

**Issue by 813nate** [qbcore-framework/qb-clothing#193]
**Describe the bug**
Players skins are not saving and/or resetting to the default ped model. This is happening randomly and not for all users. 

**To Reproduce**
Randomly happens to players when they join the server

**Expected behavior**
Player skins will save and not need to be redone

**Screenshots**
![image](https://github.com/qbcore-framework/qb-clothing/assets/137960976/6c0ba2bf-5cf5-41bd-9588-659acd5190fc)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] - less than 2 weeks ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no] - no

**Additional context**

**Comment by MentalIllness** [comment]
Seems like a local issue, have u changed the code?
