### ISSUE TITLE
OPACITY SLIDERS 

### ISSUE THREAD

**Issue by maxcapehd** [qbcore-framework/qb-clothing#194]
An opacity slider on the clothing / barber shop would be super benificial... being able to set the opacity to beards, eyebrows, makeup, lipstick and facial features would be perfect. 

This would add more customisation to players.

**Comment by xPiwel** [comment]
Secondary colors (highlight colors) on available items would be cool too... I don't really understand why it's not available tho (exemple for hairs, you can only set 1 hair color but not the highlight color > color 2) ...
