### ISSUE TITLE
[BUG] SQL Not working when it is ran

### ISSUE THREAD

**Issue by Jordan-Cache** [qbcore-framework/qb-clothing#195]
**Describe the bug**
When I try to run the sql for the clothing menu it gives me a syntax error. 

**Expected behavior**
It should add the expected tables and columns to the db

**Screenshots**
![image](https://github.com/qbcore-framework/qb-clothing/assets/140453539/cff98b09-7f10-4376-aae9-625ebddff89c)

**Questions (please complete the following information):**
 - When you last updated: A few scripts a couple days ago and some today.
 - Are you using custom resource? No other than custom vehicles and clothing and mlo's
 - Have you renamed `qb-` to something custom? No

**Comment by GenyBTW** [comment]
change "AUTO_INCREMENT" to "AUTO_INCREMENT=1" and before you run it in the query and that should fix it.

**Comment by GenyBTW** [comment]
its most likely that your database that you're running doesnt support auto. you can still use that but if you have the error again it should fix

**Comment by Wackogaming** [comment]
I'm having the same issue done what you've said still no player skins or player outfits on the database I add them in manually but it says they are there load into server get errors saying doesn't exist 🙈
