### ISSUE TITLE
needs hair highlights

### ISSUE THREAD

**Issue by heyjeay** [qbcore-framework/qb-clothing#2]
only thing missing from the script is hair highlights

**Comment by Olliekins** [comment]
Mother and Father face and skin blend is missing. 
Sun damage, blemishes, body blemishes, complexion, and chest hair are also missing from this.

**Comment by timothyscottp** [comment]
> only thing missing from the script is hair highlights

Please

**Comment by nikojr166** [comment]
I have the same problem. How can I solve it so that the hairstyle is not an outfit?
