### ISSUE TITLE
[BUG] Clothing/Character Customization Is Not Working

### ISSUE THREAD

**Issue by GamingTTRG** [qbcore-framework/qb-clothing#202]
No clothing options are switchable upon creating a character, they all just stay at 1 when you click them to switch. Same with clothing stores. Character customization is completely broken. I get this code in my console when I try: Uncaught TypeError: Cannot read properties of undefined (reading 'item') (@qb-clothing/html/script.js:546)

**Comment by GamingTTRG** [comment]
I didnt see the format earlier but I am using a fresh wipe of qbcore with no custom content whatsoever. To replicate this error you just have to create a new character and try to customize them. or even use an existing character and just try to change their clothing.

**Comment by madmechanic187** [comment]
having same issue here it will work on my home host but not on public

**Comment by daf4ever** [comment]
Just opened up a server this weekend and I ran into the same issue. Everyone is complaining that they cant change anything at the character menu. Character Menu seems to bugg out around 200+ PEDS and doesnt load the character model. All clothes options are stuck at 1. It is just a big mess at the moment.

**Comment by CapnDeath82** [comment]
Confirmed on artifact 6683

**Comment by koawhkainehighlife** [comment]
same, artificate 6683, fresh install. when you make new ped , or take basic ped to clothing store. nothing works. i ran the new query for the sql file, qbcore and clothing is listed for ensure in config. still nothing. any thoughts anyone?

**Comment by koawhkainehighlife** [comment]
> No clothing options are switchable upon creating a character, they all just stay at 1 when you click them to switch. Same with clothing stores. Character customization is completely broken. I get this code in my console when I try: Uncaught TypeError: Cannot read properties of undefined (reading 'item') (@qb-clothing/html/script.js:546)

samer error, but line 536

**Comment by Thehoodedslayers** [comment]
when you first fly in a fresh character it crashes when u get to clothing menu then if u choose a ped higher than free mode
 it crashes u also if u do /refresh skin

**Comment by musictomy** [comment]
Is there a bug, as I am admin but when I type/skin     nothing there, trying to change ped in game

**Comment by kaynegraham** [comment]
is this still an issue?

**Comment by Bloodwolf707** [comment]
THIS IS NOT FIXED YOU NEED TO STOP BEING LAZY AND FIX ALL OF THE QBOCRE CRAP THAT IS BROKEN AND STOP FUCKING WORRYING ABOUT COMPETEING WITH JIMS OVER A FUCKING MACHANIC SCRIPTS LETS FACE IT YOUR A SHITTY DEV AND UNTIL YOU FOCUS OF ALL YOUR BROKE SCRIPTS YOUR GUNNA FUCKIN STAY THAT WAY! asshole.

**Comment by GhzGarage** [comment]
@Bloodwolf707 Hey how about you go fuck yourself lol this was closed due to no response. Gotta problem with the framework go use ESX dumbass. Good way to get banned.
