### ISSUE TITLE
[BUG] Clothing Changer

### ISSUE THREAD

**Issue by SaschaB88** [qbcore-framework/qb-clothing#207]
**Describe the bug**
If you set "target = true" in the server.cfg, the clothing shops and clothing rooms for jobs work normally, but you cannot change any clothing. A change in the "config.cfg" of qb-clothing also brought no change. My PolyBox is 4x4 in the config.

**To Reproduce**
1. Go to 'server.cfg and set target to true'
2. Use the target to select the changing room. It does not get blue.
4. No Error in console, no error in server log.

**Questions (please complete the following information):**
 - When you last updated: 3 days ago
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? no

With kind regards

**Comment by madmechanic187** [comment]
same issue here

**Comment by ihustle662** [comment]
same issue as well cant change outfits

**Comment by kaynegraham** [comment]
is this still an issue?
