### ISSUE TITLE
[SUGGESTION] Can you use all Fivem Peds?

### ISSUE THREAD

**Issue by JohnDeereLiebhaber** [qbcore-framework/qb-clothing#217]
I can only use the mp_m_freemode_01 or mp_f_freemode_01 because I have a lot of clothes. If I now want to use other peds like mp_m_avongoon or a_m_m_beach_02, I see that I have almost no clothes at all. Why is that? Can you change that?

**Comment by xyced** [comment]
This is because the other peds have other components (clothing options) than the GTA:O Player Peds (mp_m_freemode_01 & mp_f_freemode_01). If you wanted to have more options for clothing for other peds, you would have to mod the ped models etc. to make more clothing for the individual ped models.

**Comment by xyced** [comment]
There are plenty of tutorials out there on youtube etc.

**Comment by KhodeVex** [comment]
Hello , All Peds In GTA Have Specefic Bones To Create Clothes , All Clothes Pack Created By Freemod Charecters bone And Just Can Use On **_mp_m_freemode_01_** and **_mp_f_freemode_01_** , if You Clothes On Other Peds U Need To Download Ready Peds With Clothes Or Create a Clothes For peds With blender Or 3D max , U Can Watch Tutorials On Youtube , Just Need Search ( Create Clothes For Peds Fivem )

**Comment by nick-perry14** [comment]
Looks like this question has been adequately answered.  Marking for closure.
