### ISSUE TITLE
Players are able to create no playerskin when creating character

### ISSUE THREAD

**Issue by Mr-Pleb** [qbcore-framework/qb-clothing#33]
How to recreate:

1. Log into a server
2. Create a new character
3. Pick an aparment
4. The system will open clothing menu
5. Press cancel
6. Log out of the server
7. Rejoin 
8. Pick the character you created
9. Spawn
10. And now you play as Michael ped

------------------------------------------------

I think the simplest solution would be to force 'mp_f_freemode_01' or 'mp_m_freemode_01' if the player chooses to cancel the default character creator.

**Comment by Mr-Pleb** [comment]
+ You can create something like this with this error
![vo7AX4k](https://user-images.githubusercontent.com/81937028/135723415-ccc21d32-3072-4a64-b650-bc12c3e2e72c.png)

**Comment by ZZG994521** [comment]
Hello! How do you solve the error phenomenon in the picture above? When I used the additional Ped and wanted to change its face and hair, this happened to my character's head.

**Comment by Mr-Pleb** [comment]
> Hello! How do you solve the error phenomenon in the picture above? When I used the additional Ped and wanted to change its face and hair, this happened to my character's head.

I am sorry but I think I am unable to help because I just removed the model selection

**Comment by Bigbearbeasttv** [comment]
NPC peds were not modeled to change components. Only a select few have options you can. If you want to change a face use the freemode peds
