### ISSUE TITLE
Unable to change the hair color of ped characters

### ISSUE THREAD

**Issue by ZZG994521** [qbcore-framework/qb-clothing#34]
When I want to change the **_hair‘s color_** of **_NPCPed_,** nothing happens. (I have tried all **_Peds that have the function of changing hair's hair color_**， But, All of them，there is **_no response_**)，Does anyone know how I should modify so that I can change the hair color of NPCPed normally？If possible, I am willing to **_pay_** for those who provide me with effective help

**Comment by Bigbearbeasttv** [comment]
Clothing menu will almost never work on NPC peds only freemode peds

**Comment by ZZG994521** [comment]
But when I added the ped modules of two characters, I still couldn't change their hair color and face. And there will be cases where the model is out of order. (I tested these two ped modules with other clothing scripts, and there were no errors)

**Comment by ZZG994521** [comment]
Obviously the problem is the face and hair of qb-clothing.

**Comment by ZZG994521** [comment]
Because when I use any NPCPed (except free mode characters), the number of face types is still ‘44’ and the number of textures is ‘15’. The two values of hair are also fixed, which may cause the original NPCPed of the game to be unable to change the face and hair color. However, when I tried to change the face, skin tone, hairstyle, and hair color of the two extra Peds(These two peds have no errors in themselves), the model was out of order.

**Comment by ZZG994521** [comment]
look like this...[https://cdn.discordapp.com/attachments/841605043479773204/894514279716376577/20211003174838_1_2_LI.jpg](url)

**Comment by Bigbearbeasttv** [comment]
thats not a clothing menu issue, thats your clothing pack issue.....
