### ISSUE TITLE
Get punched and cant put the hat and glasses again

### ISSUE THREAD

**Issue by Ranger194** [qbcore-framework/qb-clothing#48]
after  i get punched when i try to use the command /hat appear the message i dont have any hat

what can i do

**Comment by rhapidfyre** [comment]
As of March 31st on the main branch, this is still not fixed. You can take your hat/glasses on and off at will but once it gets knocked off your face it's gone until you reset your outfit.

**Comment by BerkieBb** [comment]
Well that's not a qb-clothing issue, that's something from GTA itself, if you don't want those accessories to be punched off, then use this native: https://docs.fivem.net/natives/?_0xE861D0B05C7662B8

**Comment by rhapidfyre** [comment]
> Well that's not a qb-clothing issue, that's something from GTA itself, if you don't want those accessories to be punched off, then use this native: https://docs.fivem.net/natives/?_0xE861D0B05C7662B8

I *just* saw this reply, sorry. I will add that native. I still think adding a check to see if the selected outfit contains a hat/glasses/etc would be a good idea. Getting your hat/glasses knocked off in a fight is good for realism, but being able to do /hat or /glasses again to put them back on would be beneficial.
