### ISSUE TITLE
refreshskin crashes ped models

### ISSUE THREAD

**Issue by zfbx** [qbcore-framework/qb-clothing#66]
PR https://github.com/qbcore-framework/qb-clothing/pull/36 completely hard crashes clients if using a npc ped

![error](https://cdn.discordapp.com/attachments/896619062535258132/930310524179193866/unknown.png)

Using most up to date everything as of submitting
windows
local

**Comment by ItsANoBrainer** [comment]
solved with https://github.com/qbcore-framework/qb-clothing/pull/36

**Comment by zfbx** [comment]
> solved with #36

What?.. nothing has changed in that PR.. this ticket was opened AFTER that PR...

**Comment by ItsANoBrainer** [comment]
Sorry linked the wrong PR
https://github.com/qbcore-framework/qb-clothing/pull/67
