### ISSUE TITLE
Can't change to Ped Male

### ISSUE THREAD

**Issue by Maureks** [qbcore-framework/qb-clothing#68]
Hello , when creating a character , after choosing male option , only the male default ped is available, and if switched to the next ped it only shows female peds , even when trying to get back to the number 1 ped (male default), it only shows de female option.
I haven't made any changes to the script what so ever.

my qb-framework is all up to date do the latest builds 

Is it just for me? 
What can i do? 

Thanks for the attention , and sorry for the bad english!

**Comment by MonkeyWhisper** [comment]
Cannot duplicate.
