### ISSUE TITLE
Adding Custom Clothing causing torso issue

### ISSUE THREAD

**Issue by Brusein** [qbcore-framework/qb-clothing#81]
Hi there, 

I added some custom clothes tried with 2 different packs, drag and drop ready. When doing so I lose the ability to take off my shirt and see my torso, instead I see another shirt. 

I cannot nail down why this is, the clothes drag and drop on another server fine, can anyone give me a hand if they know or let me know if they are facing the same issue?

Thank you!

**Comment by Brusein** [comment]
Any help appreciated 

Example: https://drive.google.com/file/d/18Gm0WZ_5NIG9JlC4aUYAVw9BXCtbFmGv/view?usp=sharing

**Comment by brynnie1** [comment]
How did you resolve this. Having same issue when taking pants off. Another pants is underneath
