### ISSUE TITLE
Doesn't show any presets 

### ISSUE THREAD

**Issue by Didarok** [qbcore-framework/qb-clothing#86]
Doesn't show any presets in presets tab on every job clothing locations

**Comment by Andyauk** [comment]
> Doesn't show any presets in presets tab on every job clothing locations

look in config, that added [0] = { -- Grade Level so the clothing is done though that.

**Comment by Drakoumelis** [comment]
> i don't understand what you mean. please explain it to me because i have the same problem

**Comment by Didarok** [comment]
I found the solution 
all the presets are added only for grade 0 of every JOB

**Comment by Zukey016** [comment]
> I found the solution all the presets are added only for grade 0 of every JOB

Okay but did you figure out a way to make the presets for every job grade?

**Comment by Drakoumelis** [comment]
> > I found the solution all the presets are added only for grade 0 of every JOB
> 
> Okay but did you figure out a way to make the presets for every job grade?
> 

yep im ok

**Comment by Zukey016** [comment]
> > > I found the solution all the presets are added only for grade 0 of every JOB
> > 
> > 
> > Okay but did you figure out a way to make the presets for every job grade?
> 
> yep im ok

i was asking because i need help with it

**Comment by Andyauk** [comment]
> > > > I found the solution all the presets are added only for grade 0 of every JOB
> > > 
> > > 
> > > Okay but did you figure out a way to make the presets for every job grade?
> > 
> > 
> > yep im ok
> 
> i was asking because i need help with it

I never worked it out, so I removed the two statements of the grade, untill someone hopefully. Adds something.

**Comment by bk4cs** [comment]
@Zukey016 Do you know how to make a  presets for every job grade, like Police grade 1 and police grade 2?
I tried everything and cant make it work :)
