### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by imbader** [qbcore-framework/qb-clothing#9]
commands aren't working for some reason

**Comment by imbader** [comment]
RegisterServerEvent('qb-clothing:print')
AddEventHandler('qb-clothing:print', function(data)
    print(data)
end)

QBCore.Commands.Add("helmet", "Put your helmet/cap/hat on or off..", {}, false, function(source, args)
    TriggerClientEvent("qb-clothing:client:adjustfacewear", source, 1) -- Hat
end)

QBCore.Commands.Add("glasses", "Put your glasses on or off..", {}, false, function(source, args)
	TriggerClientEvent("qb-clothing:client:adjustfacewear", source, 2)
end)

QBCore.Commands.Add("masks", "Put your mask on or off..", {}, false, function(source, args)
	TriggerClientEvent("qb-clothing:client:adjustfacewear", source, 4)
end)

**Comment by BerkieBb** [comment]
There are no commands in qb-clothing
