### ISSUE TITLE
job clothes

### ISSUE THREAD

**Issue by Drakoumelis** [qbcore-framework/qb-clothing#94]
whenever i try to go near the job clothes blip it throws an erro
![Screenshot_109](https://user-images.githubusercontent.com/88688893/159084786-1fbe035d-b6b2-4dd6-8f61-0b857c9e1d3b.png)
r

**Comment by Xensito** [comment]
Yo need to create a preset for that job

**Comment by Drakoumelis** [comment]
> Yo need to create a preset for that job 

there are presets. it just throws an error

**Comment by KaleenBhaiya00** [comment]
how to create
