### ISSUE TITLE
Config.ClothingRooms Error

### ISSUE THREAD

**Issue by LightDevil96** [qbcore-framework/qb-clothing#98]
I add new line (Only add and save)
[7] = {requiredJob = "police", coords = vector3(452.43, -990.84, 30.69), cameraLocation = vector4(452.43, -990.84, 30.69, 89.24)},
After restart server i have error
https://prnt.sc/sZfK7gl0D6zU

I having qb_policejob and ambulancejob
Using last version qbcore files

**Comment by milotiro95** [comment]
Same issue while spawning next to a clothing shop whitelisted for police or ambulance. Need to restart and spawn another place before to solve

**Comment by TonybynMp4** [comment]
[7] = {requiredJob = "police", isGang = false, coords = vector3(452.43, -990.84, 30.69), width = 5, length = 5, cameraLocation = vector4(452.43, -990.84, 30.69, 89.24)},
 
 try that maybe??

> I add new line (Only add and save) [7] = {requiredJob = "police", coords = vector3(452.43, -990.84, 30.69), cameraLocation = vector4(452.43, -990.84, 30.69, 89.24)}, After restart server i have error https://prnt.sc/sZfK7gl0D6zU
> 
> I having qb_policejob and ambulancejob Using last version qbcore files

**Comment by Grant-Daniels-Dev** [comment]
Any update? We'd love to help!

**Comment by brynnie1** [comment]
Same I try and add a further job clothing garage and still having the same issue just won't open

**Comment by MentalIllness** [comment]
This issue should be fixed in the next update ( ETA: 24 hours from now )
