### ISSUE TITLE
Preset doesn't work

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-clothing#99]
With the old and newest core and clothing shop my preset for job doesn't work. i have some preset on my config but nothing is available only my outfit. How to fix it ?

**Comment by Kalizar86** [comment]
I forget exactly what I was doing when I fixed it but I know it has something to do with the police job and and the grade level in qb-clothing/config.lua.   My guess is you're setting yourself as the chief when you give yourself the job but I think it's only setup to give the presets for grade 0 of the job.  I can't remember exactly but it's something in there.  I think I might have had to create a set for each grade.
